### ISSUE TITLE
Allowlist instead of blocklist

### ISSUE THREAD

**Issue by doozan** [rewkha/firefox-grayscale#1]
If "For all sites" is toggled then "for this site" does nothing.  Maybe instead of toggles, "For all sites" could be "color" and "grayscale" and "For this site" could be "color", "grayscale, and "default" with "color" and "grayscale" taking priority over the "For all sites" value.

**Comment by xpmn** [comment]
Updated with the both functionality - now it's possible to exclude page if "For all" is selected

**Comment by doozan** [comment]
It works, thank you!
